### ISSUE TITLE
Add TLS support?

### ISSUE THREAD

**Issue by brendanf** [conda-forge/nng-feedstock#4]
### Comment:

I'm working on packaging [the R binding for NNG](https://github.com/shikokuchuo/nanonext), which requires NNG to be compiled with TLS support.  Would you accept a pull request to add the relevant compilation flag?

Also, I'm curious why this feedstock produces only the static library for NNG rather than dynamic; I can work with this but I thought it was [discouraged by conda-forge](https://github.com/conda-forge/cfep/blob/main/cfep-18.md).

**Comment by jan-janssen** [comment]
@brendanf That sounds great - I am happy about any contributions, so feel free to open pull requests to fix these issues.

**Comment by carlodri** [comment]
added TLS for osx and linux in #5 

windows will need to wait for https://github.com/conda-forge/mbedtls-feedstock/issues/12

**Comment by brendanf** [comment]
Thanks for the fast action fixing and merging my pull request!  I sent it before bed and everything was done when I woke up!
